use thunes_cli::transaction::{CategoryWithId, Icon};

// FIXME: Add new icons
// FIXME: Set the best icon color following the background color
pub fn default_categories() -> Vec<CategoryWithId> {
    vec![
        // Transports & Travels
        CategoryWithId {
            id: ("category", "transport").into(),
            name: "Transport".to_string(),
            icon: Icon::Transport,
            color: "yellow".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "transport-travel-agency").into(),
            name: "Travel agency".to_string(),
            icon: Icon::Transport,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-accommodation").into(),
            name: "Accommodation (hotel, camping...)".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-vehicle-rental").into(),
            name: "Vehicle rental".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-taxi").into(),
            name: "Taxi".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-long-range").into(),
            name: "Long range travel".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-daily-transport").into(),
            name: "Daily transport (metro, bus...)".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        CategoryWithId {
            id: ("category", "transport-other").into(),
            name: "Transport - Other".to_string(),
            icon: Icon::Bed,
            color: "yellow".to_string(),
            parent: Some(("category", "transport").into()),
        },
        // Accommodation
        CategoryWithId {
            id: ("category", "accommodation").into(),
            name: "Accommodation".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "accommodation-other").into(),
            name: "Accommodation - other".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-clean-service").into(),
            name: "Home cleaning & services".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-insurance").into(),
            name: "Home insurance".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-water").into(),
            name: "Water".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-mortgage").into(),
            name: "Mortgage".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-energy").into(),
            name: "Energy (electricity, gaz, fuel, heating...)".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-exceptional-expenses").into(),
            name: "Exceptional expenses (moving, repair costs...)".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-rent").into(),
            name: "Rent, charges".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        CategoryWithId {
            id: ("category", "accommodation-works").into(),
            name: "Furniture, repairs, maintenance".to_string(),
            icon: Icon::Accommodation,
            color: "orange".to_string(),
            parent: Some(("category", "accommodation").into()),
        },
        // Subscriptions
        CategoryWithId {
            id: ("category", "subscription").into(),
            name: "Subscription".to_string(),
            icon: Icon::Subscription,
            color: "blue".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "subscription-other").into(),
            name: "Subscription - Other".to_string(),
            icon: Icon::Subscription,
            color: "blue".to_string(),
            parent: Some(("category", "subscription").into()),
        },
        CategoryWithId {
            id: ("category", "subscription-journal").into(),
            name: "Journal, revues...".to_string(),
            icon: Icon::Subscription,
            color: "blue".to_string(),
            parent: Some(("category", "subscription").into()),
        },
        CategoryWithId {
            id: ("category", "subscription-multimedia").into(),
            name: "Home multimedia (TV, internet...)".to_string(),
            icon: Icon::Subscription,
            color: "blue".to_string(),
            parent: Some(("category", "subscription").into()),
        },
        CategoryWithId {
            id: ("category", "subscription-phone").into(),
            name: "Phone".to_string(),
            icon: Icon::Subscription,
            color: "blue".to_string(),
            parent: Some(("category", "subscription").into()),
        },
        // Car
        CategoryWithId {
            id: ("category", "car").into(),
            name: "Car & Motorcycle".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "car-other").into(),
            name: "Car & Motorcycle - Other".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-insurance").into(),
            name: "Insurance".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-fuel").into(),
            name: "Fuel".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-fine").into(),
            name: "Fine".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-maintenance").into(),
            name: "Maintenance & Repairs".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-funding").into(),
            name: "Funding".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-parking").into(),
            name: "Parking".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        CategoryWithId {
            id: ("category", "car-toll").into(),
            name: "Toll".to_string(),
            icon: Icon::Car,
            color: "yellow".to_string(),
            parent: Some(("category", "car").into()),
        },
        // Others
        CategoryWithId {
            id: ("category", "other").into(),
            name: "Other".to_string(),
            icon: Icon::Other,
            color: "grey".to_string(),
            parent: None,
        },
        // Gifts
        CategoryWithId {
            id: ("category", "gift-and-donations").into(),
            name: "Gift & Donations".to_string(),
            icon: Icon::GiftAndDonations,
            color: "orange".to_string(),
            parent: None,
        },
        // Savings
        CategoryWithId {
            id: ("category", "savings").into(),
            name: "Savings".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "savings-other").into(),
            name: "Savings - Other".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        CategoryWithId {
            id: ("category", "savings-bank").into(),
            name: "Bank savings".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        CategoryWithId {
            id: ("category", "savings-finance").into(),
            name: "Finance savings (retirement...)".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        CategoryWithId {
            id: ("category", "savings-stocks").into(),
            name: "Stock market".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        CategoryWithId {
            id: ("category", "savings-crypto").into(),
            name: "Crypto market".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        CategoryWithId {
            id: ("category", "savings-real-estate").into(),
            name: "Real estate".to_string(),
            icon: Icon::Savings,
            color: "red".to_string(),
            parent: Some(("category", "savings").into()),
        },
        // Family
        CategoryWithId {
            id: ("category", "education-and-family").into(),
            name: "Education & Family".to_string(),
            icon: Icon::EducationAndFamily,
            color: "pink".to_string(),
            parent: None,
        },
        // Loans
        CategoryWithId {
            id: ("category", "loan").into(),
            name: "Loan".to_string(),
            icon: Icon::Loan,
            color: "red".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "loan-conso").into(),
            name: "Consumer credit".to_string(),
            icon: Icon::Loan,
            color: "red".to_string(),
            parent: Some(("category", "loan").into()),
        },
        CategoryWithId {
            id: ("category", "loan-student").into(),
            name: "Student loan".to_string(),
            icon: Icon::Loan,
            color: "red".to_string(),
            parent: Some(("category", "loan").into()),
        },
        // Pro
        CategoryWithId {
            id: ("category", "professional-fee").into(),
            name: "Professional Fee".to_string(),
            icon: Icon::ProfessionalFee,
            color: "blue".to_string(),
            parent: None,
        },
        // Taxes
        CategoryWithId {
            id: ("category", "taxes").into(),
            name: "Taxes".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "taxes-other").into(),
            name: "Taxes - Other".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        CategoryWithId {
            id: ("category", "taxes-real-estate-wealth").into(),
            name: "Real estate wealth tax".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        CategoryWithId {
            id: ("category", "taxes-income").into(),
            name: "Income tax".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        CategoryWithId {
            id: ("category", "taxes-housing").into(),
            name: "Housing tax".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        CategoryWithId {
            id: ("category", "taxes-property").into(),
            name: "Property tax".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        CategoryWithId {
            id: ("category", "taxes-employer").into(),
            name: "Employer contributions".to_string(),
            icon: Icon::Taxes,
            color: "red".to_string(),
            parent: Some(("category", "taxes").into()),
        },
        // Spare time activities
        CategoryWithId {
            id: ("category", "spare-time-activities").into(),
            name: "Spare-time Activities".to_string(),
            icon: Icon::SpareTimeActivities,
            color: "pink".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "spare-time-activities-other").into(),
            name: "Spare-time Activities - Other".to_string(),
            icon: Icon::SpareTimeActivities,
            color: "pink".to_string(),
            parent: Some(("category", "spare-time-activities").into()),
        },
        CategoryWithId {
            id: ("category", "spare-time-activities-club").into(),
            name: "Club / association (sport, hobby, art...)".to_string(),
            icon: Icon::SpareTimeActivities,
            color: "pink".to_string(),
            parent: Some(("category", "spare-time-activities").into()),
        },
        CategoryWithId {
            id: ("category", "spare-time-activities-entertainment").into(),
            name: "Entertainment (cinema, theatre, bowling...)".to_string(),
            icon: Icon::SpareTimeActivities,
            color: "pink".to_string(),
            parent: Some(("category", "spare-time-activities").into()),
        },
        CategoryWithId {
            id: ("category", "spare-time-activities-restaurants").into(),
            name: "Restaurants, bars, nightclubs...".to_string(),
            icon: Icon::SpareTimeActivities,
            color: "pink".to_string(),
            parent: Some(("category", "spare-time-activities").into()),
        },
        // Internal
        CategoryWithId {
            id: ("category", "internal-movements").into(),
            name: "Internal Movements".to_string(),
            icon: Icon::InternalMovements,
            color: "blue".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "internal-movements-external").into(),
            name: "Movements to a third party".to_string(),
            icon: Icon::InternalMovements,
            color: "blue".to_string(),
            parent: Some(("category", "internal-movements").into()),
        },
        // Withdrawal
        CategoryWithId {
            id: ("category", "cash-withdrawal").into(),

            name: "Cash Withdrawal".to_string(),
            icon: Icon::CashWithdrawal,
            color: "green".to_string(),
            parent: None,
        },
        // Health
        CategoryWithId {
            id: ("category", "health").into(),
            name: "Health".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "health-other").into(),
            name: "Health - Other".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: Some(("category", "health").into()),
        },
        CategoryWithId {
            id: ("category", "health-insurance").into(),
            name: "Complementary health insurance".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: Some(("category", "health").into()),
        },
        CategoryWithId {
            id: ("category", "health-doctor").into(),
            name: "Doctor & medical bills".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: Some(("category", "health").into()),
        },
        CategoryWithId {
            id: ("category", "health-senses").into(),
            name: "Optical care, hearing...".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: Some(("category", "health").into()),
        },
        CategoryWithId {
            id: ("category", "health-lab").into(),
            name: "Pharmacy & Lab".to_string(),
            icon: Icon::Health,
            color: "green".to_string(),
            parent: Some(("category", "health").into()),
        },
        // Everyday life
        CategoryWithId {
            id: ("category", "everyday-life").into(),
            name: "Everyday Life".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: None,
        },
        CategoryWithId {
            id: ("category", "everyday-life-other").into(),
            name: "Everyday Life - Other".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-food").into(),
            name: "Food".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-animals").into(),
            name: "Animals".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-care").into(),
            name: "Well being (hairdresser, perfumes...)".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-diy").into(),
            name: "DIY and gardening".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-electronics").into(),
            name: "Electronics".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-sport").into(),
            name: "Sports & arts equipment".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-laundromat").into(),
            name: "Laundromat & pressing".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-media").into(),
            name: "Books, CD/DVD, jewelry, toys...".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
        CategoryWithId {
            id: ("category", "everyday-life-clothes").into(),
            name: "Clothes & accessories".to_string(),
            icon: Icon::EverydayLife,
            color: "blue".to_string(),
            parent: Some(("category", "everyday-life").into()),
        },
    ]
}
