// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountIdentifiers = { name: string, id: { tb: string, id: { String: string }}, };
