// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: { tb: string, id: { String: string }}, name: string, currency: string, };
