// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export type AddTransactionOptions = { amount: number, category?: { tb: string, id: { String: string }}, description: string, tags: Array<Tag>, date?: string, };
