// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export type AddTransactionTransferOptions = { description: string, amount: number, date?: string, tags: Array<Tag>, from: { tb: string, id: { String: string }}, to: { tb: string, id: { String: string }}, };
