// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryWithId } from "./CategoryWithId";

export type Allocation = { id: { tb: string, id: { String: string }}, name: string, amount: number, category: CategoryWithId, partition: { tb: string, id: { String: string }}, };
