// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { View } from "./View";

export type Budget = { id: { tb: string, id: { String: string }}, name: string, income: number, currency: string, accounts: Array<Account>, view: View, };
