// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionCategory } from "./TransactionCategory";

export type BudgetCategory = { name: string, percentage: number, transaction_categories: Array<TransactionCategory>, color: string, };
