// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetTileType } from "./BudgetTileType";

export type BudgetTile = { t: BudgetTileType, budget: string, };
