// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Type } from "./Type";

export type Budget = { id: { tb: string, id: { String: string }}, name: string, data: Type, income: number, currency: string, accounts: Array<Account>, };
