// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icon } from "./Icon";

export type CategoryWithId = { id: { tb: string, id: { String: string }}, name: string, icon: Icon, color: string, parent?: { tb: string, id: { String: string }}, };
