// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icon } from "./Icon";

export type Category = { name: string, icon: Icon, };
