// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSplitBudgetOptions = { name: string, income: number, currency: string, accounts: { tb: string, id: { String: string }}[], };
