// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { CurrencyTileType } from "./CurrencyTileType";

export type CurrencyTile = { t: CurrencyTileType, data: Currency, };
