// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpensesAllocation } from "./ExpensesAllocation";
import type { Partition } from "./Partition";

export type ExpensesPartition = { transactions_total: number, allocations_total: number, inner: Partition, allocations: Array<ExpensesAllocation>, };
