// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Budget } from "./Budget";
import type { ExpensesPartition } from "./ExpensesPartition";

export type ExpensesBudget = { transactions_total: number, allocations_total: number, inner: Budget, partitions: Array<ExpensesPartition>, income_total: number, };
