// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allocation } from "./Allocation";
import type { TransactionWithId } from "./TransactionWithId";

export type ExpensesAllocation = { inner: Allocation, transactions: Array<TransactionWithId>, total: number, };
