// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Budget } from "./Budget";
import type { ExpensesPartition } from "./ExpensesPartition";

export type ExpensesBudget = { inner: Budget, partitions: Array<ExpensesPartition>, total: number, };
