// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryWithId } from "./CategoryWithId";
import type { TransactionWithId } from "./TransactionWithId";

export type ExpensesAllocation = { transactions_total: number, allocations_total: number, category: CategoryWithId, transactions: Array<TransactionWithId>, };
