// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyTile } from "./CurrencyTile";

export type Inner = { "type": "Currency", "data": CurrencyTile };
