// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information common to all operations types.
 */
export type Item = { amount: number, description: string, tags: Array<string>, };
