// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetTile } from "./BudgetTile";
import type { CurrencyTile } from "./CurrencyTile";

export type PortfolioTile = { id: { tb: string, id: { String: string }}, order: number, } & ({ "type": "Currency", "data": CurrencyTile } | { "type": "Budget", "data": BudgetTile });
