// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpensesPeriod } from "./ExpensesPeriod";

export type ReadExpensesOptions = { period: ExpensesPeriod, start_date: string, };
