// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionWithId } from "./TransactionWithId";

export type ReadCategoryResult = { period_start: string, period_end: string, category: { tb: string, id: { String: string }}, transactions: Array<TransactionWithId>, };
