// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadTransactionOptions = { search?: string, category?: { tb: string, id: { String: string }}, start?: string, end?: string, 
/**
 * Get transactions dated in the last `last_x_days` days before today.
 * Cannot be combined with `start` and `end` options.
 */
last_x_days?: number, };
