// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpensesBudget } from "./ExpensesBudget";

export type ReadExpensesResult = { period_start: string, period_end: string, budget: ExpensesBudget, };
