// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type Settings = { path: string, accounts_path: string, theme: Theme, tags: Array<string>, };
