// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Type } from "./Type";

export type Tile = { t: Type, account: Account, };
