// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export type TransactionWithId = { id: { tb: string, id: { String: string }}, operation: string, date: string, amount: number, description: string, tags: Array<Tag>, };
