// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transaction2 = { operation: string, date: string, amount: number, description: string, tags: Array<string>, };
