// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

export type Type = { "type": "split", "content": { categories: Array<Category>, } };
