// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAllocationOptions = { id: { tb: string, id: { String: string }}, name: string, category: { tb: string, id: { String: string }}, amount: number, partition: { tb: string, id: { String: string }}, };
