// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to display on the budget widget.
 */
export type View = { expenses: boolean, allocations: boolean, };
